### ISSUE TITLE
LmCompatibilityLevel 0 LM_KEY Wrapping

### ISSUE THREAD

**Issue by jborean93** [gssapi/gss-ntlmssp#13]
I was playing around with different NTLM versions and found that when `LmCompatibilityLevel` is `0` through the `LM_COMPAT_LEVEL` env var this mech fails to wrap the data properly when talking to a MS NTLM endpoint.

`gss-ntlmssp` is currently set up to set the `NTLMSSP_NEGOTIATE_LM_KEY` flag at this LM level and it seems like the KXKEY or maybe the SEALKEY method in MS-NLMP isn't documented properly as none of the implementations I've read or worked on handle this in a way that works in the real world.

The authentication process works, when you go to wrap the data on the client and then unwrap it on the MS server, the MS server fails saying the message or signature has been altered. If I was to compile the code and have it not set the `LM_KEY` flag the wrapping and unwrapping work just fine for the 0 LM compat level so my guess is there's something wrong with the MS docs.

Because this is woefully outdated and no one in their right mind should be using this compat level I'm all good if you just close this. Just thought I would let you know.

**Comment by simo5** [comment]
My aim is to get this to be 100% compatible with MS implementations, can you give me details of how other impls differ, or a pointer to their code and the flags you tried so I can figure out the problem?
I can then open a clarification request wrt MS-NLMP so we get this straight in docs if it is not just my misunderstanding.

**Comment by jborean93** [comment]
Fantastic, if you do figure out what the problem is I am definitely interested in hearing what the problem was.

To replicate this I've got a PowerShell script I'm using for testing at https://github.com/jborean93/pyspnego/blob/master/tests/pyspnego.ps1. I'm running the PowerShell script on Windows Server 2016, I have also tested this against Server 2008, 2008 R2, 2012, 2012 R2, and 2019 and they all behave the same.

To run this you need to do the following

* Enable inbound traffic on the port you want to use, default is [16854](https://github.com/jborean93/pyspnego/blob/513224a11a476e02ec00626c2dedad87f12e0e14/tests/pyspnego.ps1#L4), you can specify another one when calling the script with `-Port <blah>`
* Open up PowerShell as admin (right click -> Run as administrator)
* Run `C:\path\to\script\script.ps1 -Verbose`

From there you can run the following Python script

```python
#!/usr/bin/env python

import base64
import gssapi
import os
import socket
import struct


GSS_C_INQ_SSPI_SESSION_KEY = gssapi.OID.from_int_seq('1.2.840.113554.1.2.2.5.5')
NTLM = gssapi.OID.from_int_seq('1.3.6.1.4.1.311.2.2.10')


def send(s, data):
    s.sendall(struct.pack("<I", len(data)) + data)


def receive(s):
    length = struct.unpack("<I", s.recv(4))[0]
    if length:
        return s.recv(length)


def main():
    server = 'windows-host'
    port = 16854
    username = 'user@UPN'
    password = b'UserPass'

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((server, port))

    try:
        package = b"NTLM"
        s.sendall(struct.pack("<I", len(package)) + package)

        os.environ['LM_COMPAT_LEVEL'] = '0'

        user = gssapi.Name(base=username, name_type=gssapi.NameType.user)
        cred = gssapi.raw.acquire_cred_with_password(user, password, usage='initiate', mechs=[NTLM]).creds

        spn = gssapi.Name('host@%s' % server, name_type=gssapi.NameType.hostbased_service)
        flags = gssapi.RequirementFlag.confidentiality | gssapi.RequirementFlag.integrity
        context = gssapi.SecurityContext(creds=cred, usage='initiate', name=spn, mech=NTLM, flags=flags)

        in_token = None
        while not context.complete:
            if in_token:
                print("NTLM input: %s" % base64.b64encode(in_token).decode('utf-8'))

            out_token = context.step(token=in_token)

            if out_token:
                print("NTLM output: %s" % base64.b64encode(out_token).decode('utf-8'))

            send(s, out_token)
            in_token = receive(s)

        session_key = gssapi.raw.inquire_sec_context_by_oid(context, GSS_C_INQ_SSPI_SESSION_KEY)[0]
        print("Session Key: %s" % (base64.b64encode(session_key).decode('ascii')))

        print("Wrapping data")
        enc_data = context.wrap(b"Hello world", True).message
        send(s, enc_data)

        server_enc_data = receive(s)
        dec_data = context.unwrap(server_enc_data).message

        print("Unwrapped data: %s" % dec_data.decode('utf-8'))
    finally:
        s.close()


if __name__ == '__main__':
    main()
```

When you run this script here is the relevant output from the PowerShell process

```
VERBOSE: 2020-05-11T20:56:30.7132741+00:00 - RID[4] USER[DOMAIN\vagrant-domain] - Client connected from
192.168.56.1:40854, starting pipeline
VERBOSE: 2020-05-11T20:56:30.7288433+00:00 - RID[4] USER[DOMAIN\vagrant-domain] - Waiting for client connection
VERBOSE: 2020-05-11T20:56:30.7757241+00:00 - RID[5] USER[DOMAIN\vagrant-domain] - Started client pipeline for
192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7757241+00:00 - RID[5] USER[DOMAIN\vagrant-domain] - Attempting to impersonate existing
token for NT AUTHORITY\SYSTEM
VERBOSE: 2020-05-11T20:56:30.7757241+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Reading data from 192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7757241+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Trying to read 4 bytes from
192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Reading data from 192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Trying to read 32 bytes from
192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Creating server credential with the
protocol NTLM
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Creating server context
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Process token from client
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Writing 206 bytes to 192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Reading data from 192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Trying to read 216 bytes from
192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.7913501+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Process token from client
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Writing 0 bytes to 192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Reading data from 192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Trying to read 27 bytes from
192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - SessionKey: yDjbmqL2QoDi47DUtxXCmA==
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Unwrapping message from client
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Closing server context
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[NT AUTHORITY\SYSTEM] - Closing server credential
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[DOMAIN\vagrant-domain] - Disposing stream for
192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.8069775+00:00 - RID[5] USER[DOMAIN\vagrant-domain] - Disposing client socket for
192.168.56.1:40854
VERBOSE: 2020-05-11T20:56:30.8382152+00:00 - RID[5] USER[DOMAIN\vagrant-domain] - Uncaught exception, exiting listener
Exception calling "Unwrap" with "1" argument(s): "DecryptMessage() failed (The message or signature supplied for
verification has been altered, Win32ErrorCode -2146893041 - 0x8009030F)"
At line:77 char:17
+                 .$ScriptBlock @Parameters
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception


at <ScriptBlock>, <No file>: line 121
at Use-UserImpersonation, <No file>: line 77
at <ScriptBlock>, <No file>: line 148
```

Here is the output from the Python script

```
NTLM output: TlRMTVNTUAABAAAAt4IA4AAAAAAAAAAAAAAAAAAAAAA=
NTLM input: TlRMTVNTUAACAAAADAAMADgAAAC1goHi2h2NZfP6t2cAAAAAAAAAAIoAigBEAAAACgA5OAAAAA9EAE8ATQBBAEkATgACAAwARABPAE0AQQBJAE4AAQAIAEQAQwAwADEABAAYAGQAbwBtAGEAaQBuAC4AbABvAGMAYQBsAAMAIgBEAEMAMAAxAC4AZABvAG0AYQBpAG4ALgBsAG8AYwBhAGwABQAYAGQAbwBtAGEAaQBuAC4AbABvAGMAYQBsAAcACAAdE4yl1ifWAQAAAAA=
NTLM output: TlRMTVNTUAADAAAAGAAYAEgAAAAYABgAYAAAAAAAAAAAAAAANgA2AHgAAAAaABoArgAAABAAEADIAAAAtYKB4gYCAAAAAAAPa4qfUrnP+SUdRVjUI2Tb1QY1RQ2u/j75a4qfUrnP+SUdRVjUI2Tb1QY1RQ2u/j75dgBhAGcAcgBhAG4AdAAtAGQAbwBtAGEAaQBuAEAARABPAE0AQQBJAE4ALgBMAE8AQwBBAEwASgBCAE8AUgBFAEEATgAtAEwASQBOAFUAWAClWK9oNbEHUXy7yMUvfFdq
Session Key: kE1jsC7QY7vSmDQ/uhUTBQ==
Wrapping data
Traceback (most recent call last):
  File "/home/jborean/dev/pyspnego/ntlm_lm.py", line 75, in <module>
    main()
  File "/home/jborean/dev/pyspnego/ntlm_lm.py", line 66, in main
    server_enc_data = receive(s)
  File "/home/jborean/dev/pyspnego/ntlm_lm.py", line 19, in receive
    length = struct.unpack("<I", s.recv(4))[0]
struct.error: unpack requires a buffer of 4 bytes
```

We can see that MS NTLM cannot unwrap saying the message or signature is not as expected. We can also see that the derived session key differs from what gss-ntlmssp has derived `kE1jsC7QY7vSmDQ/uhUTBQ==` compared to what MS has derived `yDjbmqL2QoDi47DUtxXCmA==`.


If you set the `LM_COMPAT_LEVEL` to 1 or higher the session key matches and the code runs through correctly. This is because once the LM_COMPAT_LEVEL > 0 then `NTLMSSP_NEGOTIATE_EXTENDED_SESSION_SECURITY` is set in the flags so the LM KEY logic is not used.
 
When I was playing around with this in a Python written implementation of NTLM I came across the same problem and came to the conclusion that the logic for deriving one of the various NTLM keys when `NTLMSSP_NEGOTIATE_LM_KEY` was negotiated. When `LM_COMPAT_LEVEL > 1` then `NTLMSSP_NEGOTIATE_EXTENDED_SESSION_SECURITY` is added to the client flags and is ultimately what is used for the key derivation logic.

When applying the following git diff you can see that even when `LM_COMPAT_LEVEL` is 1 or 2 it will still fail when `NTLMSSP_NEGOTIATE_LM_KEY` was used

```
diff --git a/src/gss_sec_ctx.c b/src/gss_sec_ctx.c
index 1d8fa25..21eee07 100644
--- a/src/gss_sec_ctx.c
+++ b/src/gss_sec_ctx.c
@@ -200,13 +200,16 @@ uint32_t gssntlm_init_sec_context(uint32_t *minor_status,
             set_GSSERR(ERR_BADLMLVL);
             goto done;
         }
-        if (!gssntlm_sec_lm_ok(ctx)) {
-            ctx->neg_flags &= ~NTLMSSP_NEGOTIATE_LM_KEY;
-            ctx->neg_flags |= NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY;
-        }
-        if (!gssntlm_ext_sec_ok(ctx)) {
-            ctx->neg_flags &= ~NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY;
-        }
+        //if (!gssntlm_sec_lm_ok(ctx)) {
+        //    ctx->neg_flags &= ~NTLMSSP_NEGOTIATE_LM_KEY;
+        //    ctx->neg_flags |= NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY;
+        //}
+        //if (!gssntlm_ext_sec_ok(ctx)) {
+        //    ctx->neg_flags &= ~NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY;
+        //}
+
+        ctx->neg_flags |= NTLMSSP_NEGOTIATE_LM_KEY;
+        ctx->neg_flags &= ~NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY;
 
         retmin = ntlm_init_ctx(&ctx->ntlm);
         if (retmin) {
```

I also tried to remove the `NTLMSSP_NEGOTIATE_KEY_EXCH` to see if maybe that was the problem but that's not the case. I haven't tried using a weaker key (`&= ~NTLMSSP_NEGOTIATE_KEY_128`).

What is interesting is that the MS-NLMP docs actually have an example response of the `KeyExchangeKey` and the `EncryptedRandomSessionKey` when `NTLMSSP_NEGOTIATE_LM_KEY` is set. In a Python implementation of NTLM for [ComputeResponse](https://github.com/jborean93/pyspnego/blob/f1e67cece9a8f48f28d3474384da397a0e4d7b0a/spnego/_ntlm_raw/crypto.py#L84-L151) and [KXKEY](https://github.com/jborean93/pyspnego/blob/f1e67cece9a8f48f28d3474384da397a0e4d7b0a/spnego/_ntlm_raw/crypto.py#L276-L307) I'm getting the [following results](https://github.com/jborean93/pyspnego/blob/f1e67cece9a8f48f28d3474384da397a0e4d7b0a/tests/_ntlm_raw/test_crypto.py#L110-L127)

* `KeyExchangeKey`: B0 9E 37 9F 7F BE CB 1E AF 0A FD CB 03 83 C8 A0
* `EncryptedRandomSessionKey`: 4C D7 BB 57 D6 97 EF 9B 54 9F 02 B8 F9 B3 78 64

These correlate with the MS-NLMP expected results for the [KeyExchangeKey](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/859a18d1-d7b2-4e98-a261-5b38cdf4b11d) and the [EncryptedRandomSessionKey](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/2d7f9599-f849-4550-9579-91aeea8078b0) examples with those flags.

Let me know if you need any more data.

**Comment by simo5** [comment]
Wow this info level is absolutely amazing, thanks a lot.
I will take a careful look and see if I can spot anything out of place.
Are you willing to try some patches with your setup?

**Comment by jborean93** [comment]
> Wow this info level is absolutely amazing, thanks a lot.

I've been knee deep in all this stuff recently so being able to test against actual real world implementations and get useful info has been a big priority for me.

> Are you willing to try some patches with your setup?

Of course, definitely curious as to what the actual issue is.

**Comment by simo5** [comment]
So big question is, are you expecting to use real LM keys?
Because the code here hardcodes a NoLMResponseNTLMv1 to true.
Could you quickly check if results are successful for you switching it off in gssntlm_cli_auth() ?

**Comment by jborean93** [comment]
It's still a problem unfortunately.

```yaml
# Auth with NoLMResposneNTLMv1 = true
MessageType: NtlmAuthenticate (3)
Signature: "NTLMSSP\0"
Data:
  LmChallengeResponseFields:
    Len: 24
    MaxLen: 24
    BufferOffset: 72
  NtChallengeResponseFields:
    Len: 24
    MaxLen: 24
    BufferOffset: 96
  DomainNameFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 0
  UserNameFields:
    Len: 54
    MaxLen: 54
    BufferOffset: 120
  WorkstationFields:
    Len: 26
    MaxLen: 26
    BufferOffset: 174
  EncryptedRandomSessionKeyFields:
    Len: 16
    MaxLen: 16
    BufferOffset: 200
  NegotiateFlags:
    raw: 3800138421
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_KEY_EXCH (1073741824)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_VERSION (33554432)
    - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
    - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_LM_KEY (128)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  Version:
    Major: 6
    Minor: 2
    Build: 0
    Reserved: '000000'
    NTLMRevision: 15
  MIC:
  Payload:
    LmChallengeResponse:
      ResponseType: LMv1
      LMProofStr: D2B798C11547F5504ABABD48BEBD212E1D449745C0EF4D9C
    NtChallengeResponse:
      ResponseType: NTLMv1
      NTProofStr:
      - D2B798C11547F5504ABABD48BEBD212E1D449745C0EF4D9C
    DomainName:
    UserName: vagrant-domain@DOMAIN.LOCAL
    Workstation: JBOREAN-LINUX
    EncryptedRandomSessionKey: D7A449601A38F43B30D0753291767D71
  SessionKey: E0D59DAC773EF6533EC0AD9951C16715
RawData: 4E544C4D535350000300000018001800480000001800180060000000000000000000000036003600780000001A001A00AE00000010001000C8000000B58281E2060200000000000FD2B798C11547F5504ABABD48BEBD212E1D449745C0EF4D9CD2B798C11547F5504ABABD48BEBD212E1D449745C0EF4D9C760061006700720061006E0074002D0064006F006D00610069006E00400044004F004D00410049004E002E004C004F00430041004C004A0042004F005200450041004E002D004C0049004E0055005800D7A449601A38F43B30D0753291767D71
```

```yaml
# Auth with NoLMResponseNTLMv1 = false
MessageType: NtlmAuthenticate (3)
Signature: "NTLMSSP\0"
Data:
  LmChallengeResponseFields:
    Len: 24
    MaxLen: 24
    BufferOffset: 72
  NtChallengeResponseFields:
    Len: 24
    MaxLen: 24
    BufferOffset: 96
  DomainNameFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 0
  UserNameFields:
    Len: 54
    MaxLen: 54
    BufferOffset: 120
  WorkstationFields:
    Len: 26
    MaxLen: 26
    BufferOffset: 174
  EncryptedRandomSessionKeyFields:
    Len: 16
    MaxLen: 16
    BufferOffset: 200
  NegotiateFlags:
    raw: 3800138421
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_KEY_EXCH (1073741824)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_VERSION (33554432)
    - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
    - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_LM_KEY (128)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  Version:
    Major: 6
    Minor: 2
    Build: 0
    Reserved: '000000'
    NTLMRevision: 15
  MIC:
  Payload:
    LmChallengeResponse:
      ResponseType: LMv1
      LMProofStr: FFC81729E4787277EA19D1F9ED2A9475828042D11C26F1E0
    NtChallengeResponse:
      ResponseType: NTLMv1
      NTProofStr:
      - F21380C3EAF591093D2A8573C421EC0DC1721A3AEF51F8BE
    DomainName:
    UserName: vagrant-domain@DOMAIN.LOCAL
    Workstation: JBOREAN-LINUX
    EncryptedRandomSessionKey: 3C6153BDE4889C889661DB25AE66AB8D
  SessionKey: 04067F279851F99BB8A21E444623BA8C
RawData: 4E544C4D535350000300000018001800480000001800180060000000000000000000000036003600780000001A001A00AE00000010001000C8000000B58281E2060200000000000FFFC81729E4787277EA19D1F9ED2A9475828042D11C26F1E0F21380C3EAF591093D2A8573C421EC0DC1721A3AEF51F8BE760061006700720061006E0074002D0064006F006D00610069006E00400044004F004D00410049004E002E004C004F00430041004C004A0042004F005200450041004E002D004C0049004E00550058003C6153BDE4889C889661DB25AE66AB8D
```

**Comment by jborean93** [comment]
When I remove the `NTLMSSP_NEGOTIATE_KEY_EXCH` flag the actual session key should just be the result of [KXKEY](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/d86303b5-b29e-4fb9-b119-77579c761370). So a mismatch in the reported exported session key from gss-ntlmssp and the MS implementation would indicate that the logic for KXKEY is incorrect in this scenario.

Looking at the function it takes the following input

* `SessionBaseKey` - Is just `MD4(NTOWF)`, we know we have the proper NT hash here because auth is working just fine
* `LmChallengeResponse` - Will be based on the `NoLMResponseNTLMv1` as to whether this is the NT response or a unique LM response value. Tried both scenarios so I don't think this is it
* `LMOWF` - We know the current logic for this value is correct as auth is working
* `ServerChallenge` - Pretty simple, derived from the challenge message, no extra processing happening here

The actual logic when `NTLMSSP_NEGOTIATE_LMKEY` is

```
ConcatenationOf(
    DES(LMOWF[0..6], LmChallengeResponse[0..7]), 
    DES(ConcatenationOf(LMOWF[7], 0xBDBDBDBDBDBD), LmChallengeResponse[0..7])
)
```

Seems pretty simple but uses a constant which may be documented incorrectly, unfortunately MS would probably have to confirm this.

**Comment by simo5** [comment]
If these are throwaway credentials that you are getting, would you mind providing me the session key generated by a windows host as well as causing gssntlmssp to print intermediate values ?
So I can try variations on the computation ?

**Comment by jborean93** [comment]
Sure

| Username | Password | Server Challenge (HEX) | gss-ntlmssp Session Key (HEX) | MS Session Key (HEX) |
|:---------------------------:|-------------:|------------------------|----------------------------------|----------------------------------|
| vagrant-domain@DOMAIN.LOCAL | VagrantPass1 | 4556B569C9536A31 | E9A9889CB97F647DA3AA9C3CAAC662E6 | 5FFA2BF727ADD101C26CF2E6C113BD6D |

```yaml
MessageType: NtlmNegotiate (1)
Signature: "NTLMSSP\0"
Data:
  NegotiateFlags:
    raw: 2684388023
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_LM_KEY (128)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_OEM (2)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  DomainNameFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 0
  WorkstationFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 0
  Version:
  Payload:
    DomainName:
    Workstation:
RawData: 4E544C4D5353500001000000B78200A000000000000000000000000000000000
```

```yaml
MessageType: NtlmChallenge (2)
Signature: "NTLMSSP\0"
Data:
  TargetNameFields:
    Len: 12
    MaxLen: 12
    BufferOffset: 56
  NegotiateFlags:
    raw: 2726396597
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_VERSION (33554432)
    - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
    - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_LM_KEY (128)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  ServerChallenge: 4556B569C9536A31
  Reserved: '0000000000000000'
  TargetInfoFields:
    Len: 138
    MaxLen: 138
    BufferOffset: 68
  Version:
    Major: 10
    Minor: 0
    Build: 14393
    Reserved: '000000'
    NTLMRevision: 15
  Payload:
    TargetName: DOMAIN
    TargetInfo:
    - AvId: MSV_AV_NB_DOMAIN_NAME (2)
      Value: DOMAIN
    - AvId: MSV_AV_NB_COMPUTER_NAME (1)
      Value: DC01
    - AvId: MSV_AV_DNS_DOMAIN_NAME (4)
      Value: domain.local
    - AvId: MSV_AV_DNS_COMPUTER_NAME (3)
      Value: DC01.domain.local
    - AvId: MSV_AV_DNS_TREE_NAME (5)
      Value: domain.local
    - AvId: MSV_AV_TIMESTAMP (7)
      Value: '2020-05-12T21:23:17.9647183Z'
    - AvId: MSV_AV_EOL (0)
      Value:
RawData: 4E544C4D53535000020000000C000C0038000000B58281A24556B569C9536A3100000000000000008A008A00440000000A0039380000000F44004F004D00410049004E0002000C0044004F004D00410049004E000100080044004300300031000400180064006F006D00610069006E002E006C006F00630061006C000300220044004300300031002E0064006F006D00610069006E002E006C006F00630061006C000500180064006F006D00610069006E002E006C006F00630061006C0007000800CF04E98DA328D60100000000
```

```yaml
MessageType: NtlmAuthenticate (3)
Signature: "NTLMSSP\0"
Data:
  LmChallengeResponseFields:
    Len: 24
    MaxLen: 24
    BufferOffset: 72
  NtChallengeResponseFields:
    Len: 24
    MaxLen: 24
    BufferOffset: 96
  DomainNameFields:
    Len: 0
    MaxLen: 0
    BufferOffset: 0
  UserNameFields:
    Len: 54
    MaxLen: 54
    BufferOffset: 120
  WorkstationFields:
    Len: 26
    MaxLen: 26
    BufferOffset: 174
  EncryptedRandomSessionKeyFields:
    Len: 16
    MaxLen: 16
    BufferOffset: 200
  NegotiateFlags:
    raw: 2726396597
    flags:
    - NTLMSSP_NEGOTIATE_56 (2147483648)
    - NTLMSSP_NEGOTIATE_128 (536870912)
    - NTLMSSP_NEGOTIATE_VERSION (33554432)
    - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
    - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
    - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
    - NTLMSSP_NEGOTIATE_NTLM (512)
    - NTLMSSP_NEGOTIATE_LM_KEY (128)
    - NTLMSSP_NEGOTIATE_SEAL (32)
    - NTLMSSP_NEGOTIATE_SIGN (16)
    - NTLMSSP_REQUEST_TARGET (4)
    - NTLMSSP_NEGOTIATE_UNICODE (1)
  Version:
    Major: 6
    Minor: 2
    Build: 0
    Reserved: '000000'
    NTLMRevision: 15
  MIC:
  Payload:
    LmChallengeResponse:
      ResponseType: LMv1
      LMProofStr: 8BFCFED5A36D251386CC38DE78BAE16224C52FD735355E24
    NtChallengeResponse:
      ResponseType: NTLMv1
      NTProofStr:
      - C0285BD706E92151930273E31B5B1566C2CB2EB9C8C54EF0
    DomainName:
    UserName: vagrant-domain@DOMAIN.LOCAL
    Workstation: JBOREAN-LINUX
    EncryptedRandomSessionKey: '00000000000000000000000000000000'
  SessionKey: E9A9889CB97F647DA3AA9C3CAAC662E6
RawData: 4E544C4D535350000300000018001800480000001800180060000000000000000000000036003600780000001A001A00AE00000010001000C8000000B58281A2060200000000000F8BFCFED5A36D251386CC38DE78BAE16224C52FD735355E24C0285BD706E92151930273E31B5B1566C2CB2EB9C8C54EF0760061006700720061006E0074002D0064006F006D00610069006E00400044004F004D00410049004E002E004C004F00430041004C004A0042004F005200450041004E002D004C0049004E005500580000000000000000000000000000000000
```

Changes I made to gss-ntlmssp in this exchange

* Using `LM_COMPAT_LEVEL=0`
* Set `NoLMResponseNTLMv1 = false` so the LMChallengeResponse is set and not just the `NTChallengeResponse`
* Unset `NTLMSSP_NEGOTIATE_KEY_EXCH` so the exported session key should just be the KeyExchangeKey for easier cross checking
